/**
 * Integration tests for Codex agent conversion and file sync.
 */

import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';

const mockFetchSubagentContent = vi.fn();

vi.mock('../../lib/subagents.js', async () => {
  const actual = await vi.importActual('../../lib/subagents.js');
  return {
    ...actual,
    fetchSubagentContent: mockFetchSubagentContent,
  };
});

const {
  checkCodexAgentUpdates,
  convertSubagentMarkdownToCodexToml,
  listInstalledCodexAgents,
  syncCodexAgents,
} = await import('../../lib/codex-agents.js');

function makeTempDir() {
  return mkdtempSync(join(tmpdir(), 'codex-agents-test-'));
}

describe('Codex Agents Conversion', () => {
  let tempDir;

  beforeEach(() => {
    tempDir = makeTempDir();
    mockFetchSubagentContent.mockReset();
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  it('should convert a Markdown subagent into Codex TOML', () => {
    const markdown = `---
name: Code Reviewer
description: Reviews pull requests for bugs
---

# Review Checklist

Look for correctness issues first.`;

    const converted = convertSubagentMarkdownToCodexToml(markdown, 'code-review.agent.md');

    expect(converted.outputFilename).toBe('code-review.toml');
    expect(converted.toml).toContain('# Generated by @supercorks/skills-installer from code-review.agent.md');
    expect(converted.toml).toContain('name = "code_reviewer"');
    expect(converted.toml).toContain('description = "Reviews pull requests for bugs"');
    expect(converted.toml).toContain("developer_instructions = '''");
    expect(converted.toml).toContain('Look for correctness issues first.');
  });

  it('should only detect installer-generated Codex agent files', async () => {
    writeFileSync(
      join(tempDir, 'developer.toml'),
      '# Generated by @supercorks/skills-installer from developer.agent.md\nname = "developer"\ndescription = "Developer"\ndeveloper_instructions = """\nBuild things\n"""\n',
      'utf8'
    );
    writeFileSync(
      join(tempDir, 'manual.toml'),
      'name = "manual"\ndescription = "Manual agent"\ndeveloper_instructions = """\nDo not touch\n"""\n',
      'utf8'
    );

    const installed = await listInstalledCodexAgents(tempDir);

    expect(installed).toEqual(['developer.agent.md']);
  });

  it('should sync selected Codex agents and preserve unrelated TOML files', async () => {
    writeFileSync(
      join(tempDir, 'old-agent.toml'),
      '# Generated by @supercorks/skills-installer from old-agent.agent.md\nname = "old_agent"\ndescription = "Old agent"\ndeveloper_instructions = """\nOld\n"""\n',
      'utf8'
    );
    writeFileSync(
      join(tempDir, 'manual.toml'),
      'name = "manual"\ndescription = "Manual agent"\ndeveloper_instructions = """\nKeep me\n"""\n',
      'utf8'
    );

    mockFetchSubagentContent.mockImplementation(async (filename) => {
      if (filename === 'developer.agent.md') {
        return `---\nname: Developer\ndescription: Builds features\n---\n\nImplement the requested change.`;
      }
      if (filename === 'tester.agent.md') {
        return `---\nname: Tester\ndescription: Verifies behavior\n---\n\nRun targeted tests and report failures.`;
      }
      throw new Error(`Unexpected filename: ${filename}`);
    });

    await syncCodexAgents(tempDir, ['developer.agent.md', 'tester.agent.md']);

    const developerToml = readFileSync(join(tempDir, 'developer.toml'), 'utf8');
    const testerToml = readFileSync(join(tempDir, 'tester.toml'), 'utf8');
    const manualToml = readFileSync(join(tempDir, 'manual.toml'), 'utf8');

    expect(developerToml).toContain('name = "developer"');
    expect(testerToml).toContain('name = "tester"');
    expect(manualToml).toContain('Keep me');
    expect(() => readFileSync(join(tempDir, 'old-agent.toml'), 'utf8')).toThrow();
  });

  it('should report updates when generated TOML differs from the current source conversion', async () => {
    writeFileSync(
      join(tempDir, 'developer.toml'),
      '# Generated by @supercorks/skills-installer from developer.agent.md\nname = "developer"\ndescription = "Developer"\ndeveloper_instructions = """\nOld body\n"""\n',
      'utf8'
    );

    mockFetchSubagentContent.mockResolvedValue(`---\nname: Developer\ndescription: Developer\n---\n\nNew body`);

    const updates = await checkCodexAgentUpdates(tempDir, ['developer.agent.md']);

    expect(Array.from(updates)).toEqual(['developer.agent.md']);
  });
});
