/**
 * Convert Markdown subagent definitions into Codex TOML custom agents.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';
import { homedir } from 'os';
import { fetchSubagentContent, humanizeAgentName, parseSubagentDefinition } from './subagents.js';

const GENERATED_COMMENT_PREFIX = '# Generated by @supercorks/skills-installer from ';

function resolvePath(path) {
  if (path === '~') return homedir();
  if (path.startsWith('~/')) return resolve(homedir(), path.slice(2));
  return resolve(path);
}

export function codexTomlFilenameForAgent(agentFilename) {
  return `${agentFilename.replace(/\.agent\.md$/i, '')}.toml`;
}

export function codexAgentNameForAgent(agentFilename, displayName = '') {
  const preferred = displayName || agentFilename.replace(/\.agent\.md$/i, '');
  return preferred
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '') || 'agent';
}

function escapeTomlBasicString(value) {
  return String(value)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, ' ')
    .trim();
}

function formatDeveloperInstructions(body) {
  const normalizedBody = (body || '').replace(/\r\n/g, '\n').trim();
  if (!normalizedBody) {
    return "developer_instructions = '''\nAct as the requested specialist and complete the assigned task.\n'''";
  }

  if (!normalizedBody.includes("'''")) {
    return `developer_instructions = '''\n${normalizedBody}\n'''`;
  }

  const escaped = normalizedBody
    .replace(/\\/g, '\\\\')
    .replace(/"""/g, '\\"\\"\\"');

  return `developer_instructions = """\n${escaped}\n"""`;
}

export function convertSubagentMarkdownToCodexToml(content, agentFilename) {
  const definition = parseSubagentDefinition(content, agentFilename);
  const outputFilename = codexTomlFilenameForAgent(agentFilename);
  const codexName = codexAgentNameForAgent(agentFilename, definition.name);
  const description = definition.description || `${humanizeAgentName(agentFilename)} custom agent`;

  const toml = [
    `${GENERATED_COMMENT_PREFIX}${agentFilename}`,
    `name = "${escapeTomlBasicString(codexName)}"`,
    `description = "${escapeTomlBasicString(description)}"`,
    formatDeveloperInstructions(definition.body),
    '',
  ].join('\n');

  return {
    sourceFilename: agentFilename,
    outputFilename,
    name: definition.name,
    description,
    toml,
  };
}

function parseGeneratedSourceFilename(tomlContent, outputFilename) {
  const commentMatch = tomlContent.match(/^# Generated by @supercorks\/skills-installer from ([^\n]+)$/m);
  if (commentMatch) {
    return commentMatch[1].trim();
  }

  return null;
}

function listGeneratedCodexAgentEntries(targetPath) {
  const absolutePath = resolvePath(targetPath);
  if (!existsSync(absolutePath)) {
    return [];
  }

  return readdirSync(absolutePath)
    .filter(name => name.endsWith('.toml'))
    .map(outputFilename => {
      const absoluteFilePath = join(absolutePath, outputFilename);
      const content = readFileSync(absoluteFilePath, 'utf8');
      const sourceFilename = parseGeneratedSourceFilename(content, outputFilename);
      if (!sourceFilename) {
        return null;
      }

      return {
        sourceFilename,
        outputFilename,
        absoluteFilePath,
        content,
      };
    })
    .filter(Boolean);
}

export async function listInstalledCodexAgents(targetPath) {
  return listGeneratedCodexAgentEntries(targetPath).map(entry => entry.sourceFilename);
}

export async function checkCodexAgentUpdates(targetPath, agentFilenames) {
  const installedEntries = listGeneratedCodexAgentEntries(targetPath);
  const bySourceFilename = new Map(installedEntries.map(entry => [entry.sourceFilename, entry]));
  const needsUpdate = new Set();

  for (const agentFilename of agentFilenames) {
    const entry = bySourceFilename.get(agentFilename);
    if (!entry) {
      continue;
    }

    try {
      const content = await fetchSubagentContent(agentFilename);
      const converted = convertSubagentMarkdownToCodexToml(content, agentFilename);
      if (converted.toml !== entry.content) {
        needsUpdate.add(agentFilename);
      }
    } catch {
      // Skip update markers when the remote file cannot be fetched.
    }
  }

  return needsUpdate;
}

export async function syncCodexAgents(targetPath, agentFilenames, onProgress = () => {}) {
  const absolutePath = resolvePath(targetPath);
  mkdirSync(absolutePath, { recursive: true });

  const existingEntries = listGeneratedCodexAgentEntries(absolutePath);
  const selectedSet = new Set(agentFilenames);

  for (const entry of existingEntries) {
    if (!selectedSet.has(entry.sourceFilename) && existsSync(entry.absoluteFilePath)) {
      rmSync(entry.absoluteFilePath, { force: true });
    }
  }

  for (let index = 0; index < agentFilenames.length; index += 1) {
    const agentFilename = agentFilenames[index];
    onProgress(`Converting ${index + 1}/${agentFilenames.length}: ${agentFilename}`);
    const content = await fetchSubagentContent(agentFilename);
    const converted = convertSubagentMarkdownToCodexToml(content, agentFilename);
    writeFileSync(join(absolutePath, converted.outputFilename), converted.toml, 'utf8');
  }

  onProgress('Done!');
}